port: 8080
db_conn_str: "host=postgres port=5432 user=coordinator_user password=coordinator_password dbname=coordinator_db sslmode=disable"
heartbeat_delay: 60000000000
dead_delay: 60000000000
task_timeout: 60000000000
task_retries: 3