services:
  coordinator:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    container_name: coordinator
    ports:
      - "8080:8080"
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - COORDINATOR_ADDRESS=http://coordinator:8080
    depends_on:
      - coordinator
    networks:
      - app-network
    scale: 3

networks:
  app-network:
    driver: host