services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: coordinator_user
      POSTGRES_PASSWORD: coordinator_password
      POSTGRES_DB: coordinator_db
      POSTGRESQL_MAX_CONNECTIONS: "200"
    volumes:
      - pgdata_primary:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coordinator_user -d coordinator_db"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  coordinator:
    build:
      context: .
      dockerfile: coordinator_main/Dockerfile
    container_name: coordinator
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: coordinator_user
      DB_PASSWORD: coordinator_password
      DB_NAME: coordinator_db
      RABBITMQ_URL: "amqp://admin:secret@rabbitmq:5672/"
      EXCHANGE_NAME: "tasks_direct"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: worker_main/Dockerfile
    environment:
      COORDINATOR_ADDR: "coordinator:8080"
      RABBITMQ_URL: "amqp://admin:secret@rabbitmq:5672/"
      EXCHANGE_NAME: "tasks_direct"
    depends_on:
      - coordinator
    networks:
      - app-network
    scale: 2

networks:
  app-network:
    driver: bridge

volumes:
  pgdata_primary:
  rabbitmq_data: